services:
  acc:
    image: lipanski/docker-static-website:latest
    restart: always
    volumes:
      - ./:/home/static
      - ./httpd.conf:/home/static/httpd.conf:ro
    # Point to your reverse proxy network
    networks:
      - web

networks:
  web:
    external: true