services:
  acc:
    image: lipanski/docker-static-website:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/static
      - ./httpd.conf:/home/static/httpd.conf:ro